.PHONY: all lint test eval visualizer clean

install: .venv requirements.txt requirements-dev.txt
	uv pip install -r requirements-dev.txt

all: install lint test

.venv:
	uv venv

requirements.txt: requirements.in
	uv pip compile requirements.in -o requirements.txt

requirements-dev.txt: requirements-dev.in requirements.in
	uv pip compile requirements-dev.in -o requirements-dev.txt

lint:
	uv run ruff check --fix src/ tests/
	uv run ruff format src/ tests/
	uv run mypy src/

test:
	uv run pytest tests/

# Usage: make eval MODEL=claude-haiku-4-5 PROVIDER=anthropic TASKS=data/tasks/search_agent_v1.json [EFFORT=medium]
eval:
	uv run python -m src.cli --model $(MODEL) --provider $(PROVIDER) --tasks $(TASKS) $(if $(EFFORT),--effort $(EFFORT))

# Rebuild the offline dashboard (viz/visualizer.html, data inlined, opens under file://).
# The Pages build (viz/pages-index.html) is regenerated by viz/deploy_pages.sh on deploy.
# Both are generated artifacts and are gitignored.
visualizer:
	uv run python viz/build_visualizer.py

clean:
	rm -rf .venv .mypy_cache .ruff_cache .pytest_cache __pycache__ requirements.txt requirements-dev.txt
